[project]
name = "russian"
version = "0.1.0"
description = "Russian notes"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-macros-plugin>=1.5.0",
    "mkdocs-material>=9.7.1",
    "mkdocs-simple-hooks>=0.1.5",
]
